# Generated by Django 3.2.5 on 2021-07-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('prod_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('prod_price', models.IntegerField(max_length=5)),
            ],
        ),
    ]
