# Generated by Django 3.2.5 on 2021-07-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_price',
            field=models.IntegerField(),
        ),
    ]
