# Generated by Django 3.2.5 on 2021-07-16 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_products_prod_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='prod_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
