# Generated by Django 3.2.5 on 2021-07-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_products_prod_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
