# Generated by Django 3.2.5 on 2021-07-17 04:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_buy_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_details',
            name='prod_ordered',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='home.products'),
            preserve_default=False,
        ),
    ]
